# Generated by Django 3.1.2 on 2020-11-20 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopembelajaran',
            old_name='name',
            new_name='materi',
        ),
        migrations.AddField(
            model_name='videopembelajaran',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
